### PR TITLE
pack-version-updates

### PR DESCRIPTION
**Pull request by resmaa**
Version Updates on a few packs.

### CODE REVIEW

**Comment by spectro-prow** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/spectrocloud/librarium/pull/617#" title="Author self-approved">resmaa</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=spectrocloud%2Flibrarium).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/spectrocloud/librarium/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by spectro-prow** [comment]
Hi @resmaa. Thanks for your PR.

I'm waiting for a [spectrocloud](https://github.com/orgs/spectrocloud/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/spectrocloud/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=spectrocloud%2Flibrarium).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Review by Siboney1 — CHANGES_REQUESTED** [review]
Please review all feedback and include the proposed updates before merging. If you have any questions, kindly reach out to me. thx

**Comment by resmaa** [comment]
> 1. Capitalize the C in first sentence to look like this Cert-manager. -- https://cert-manager.io/docs/ c needs to be small 
> 2. Remove the comma after _clusters_ and before _and_.
> 3. Added comma after renewing.
> 4. Remove the comma after validity and before the and.
> 5. Added _s_ to _attempt_.
> 
> Cert-manager adds certificates and certificate issuers as resource types in Kubernetes clusters and simplifies the process of obtaining, renewing, and using those certificates. It can issue certificates from a variety of supported sources, including Let’s Encrypt, HashiCorp Vault, and Venafi as well as private PKI. It also takes care of the certificate validity and attempts to renew certificates before expiry.

**Comment by resmaa** [comment]
> 3\. bash

'bash' is not required for kubectl commands

**Comment by resmaa** [comment]
> I've made some edits. Please review the attached file. I'd like to replace this entry below from <Accessing the Dashboard heading till the end of the document.
> 
> ## Accessing the Dashboard
> **ClusterIP service type**
> 
> 1. When connected to the cluster remotely, run the following command to establish a connection to Dashboard deployment on _port 8080_.
>    `bash kubectl port-forward -n kubernetes-dashboard service/kubernetes-dashboard 8080:443`
> 2. To access the **Kubernetes Dashboard**, go to a web browser of your choice and type:
>    `https://localhost:8080`.
> 3. From a Terminal window, type the following command to get the Bearer token for the **Dashboard Login** page:
>    `bash kubectl -n kubernetes-dashboard describe secret $(kubectl -n kubernetes-dashboard get secret | grep kubernetes-dashboard-token | awk '{print $1}')`
>    The output of the above command will look like this, where the token value is in the last line.
>    ```yaml
>    Name:         kubernetes-dashboard-token-h4lnf
>    Namespace:    kubernetes-dashboard
>    Labels:       <none>
>    Annotations:  kubernetes.io/service-account.name: kubernetes-dashboard
>                kubernetes.io/service-account.uid: 00e729f1-6638-4e68-8df5-afa2e2e38095
>    
>    Type:  kubernetes.io/service-account-token
>    
>    Data
>    ====
>    ca.crt:     1029 bytes
>    namespace:  20 bytes
>    token:      eyJhbGciOiJSUzI1NiIsImtpZCI6Ilg1bTg3RWM4Y1c3NnhkQ3dXbXNDUXQydVpYQklRUWoxa1BaS0ctVkVTSDQifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlcm5ldGVzLWRhc2hib2FyZCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJrdWJlcm5ldGVzLWRhc2hib2FyZC10b2tlbi1oNGxuZiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJrdWJlcm5ldGVzLWRhc2hib2FyZCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjAwZTcyOWYxLTY2MzgtNGU2OC04ZGY1LWFmYTJlMmUzODA5NSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlcm5ldGVzLWRhc2hib2FyZDprdWJlcm5ldGVzLWRhc2hib2FyZCJ9.JU4GOJNjGpkHabUyxBt_2rvtXNjpR3w238BF2oMCQUNf_ZkUGSMeAAgIKxbAuk62dtJNDaRh5yAZ9J5KthMcU6k4qVmodUOJdlvigBVNjTDEhPM-sqJus62HMtwjpvm0CX-aP_A_BqHs2yJ3OgXSX0uHmkUO1FMoZSVaRpOvx7f5bPswxd87L3npuZt4p-NJIX32-DGjBnxdANAHcWil3YHIUbDgQIdjDfN6stGU_JByvzfCJpNCWWDinr772W7iZ3uA28F8uGS0ZMd1E5e1moEFBY8BM015Qxg2Y_k7lmv9S8GMkBJyTiJNiqnwLwfsiE1ycE4Tgq_vuQfFToIMNw
>    ```
> 
> **LoadBalancer service type**
> 
> Use the _LoadBalancer_ Service IP & Port to connect to the Dashboard.
> 
> ## Ingress
> Follow these steps to configure Ingress on the **Kubernetes Dashboard**:
> 
> 1. Change the serviceType from _LoadBalancer_ to _ClusterIP_ (line [integrations start #17](https://github.com/spectrocloud/librarium/pull/17)).
> 2. Ingress (line [Mihai/fixes #23](https://github.com/spectrocloud/librarium/pull/23))
>    
>    * Enable Ingress - change **Enabled** from _false_ to _true_.
>    * Set Ingress rules like **annotations**, **path**, **hosts**, etc.
> 
> With these config changes, you can access the **Kubernetes Dashboard** service on the Ingress Controller LoadBalancer hostname/IP.
> 
> ## Troubleshooting
> If the **Kubernetes Dashboard** is not accessible, check the Dashboard pod for errors and ensure the Dashboard service is in the _Running_ state.
> 
> When the **Namespace** is customized while deploying **Kubernetes Dashboard**, make sure to replace the **Namespace** values in the above commands.
> 
> ## References
> https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/ https://github.com/kubernetes/dashboard/tree/master/docs https://kubernetes.io/docs/concepts/services-networking/ingress/

'bash' is not required for kubectl commands

**Comment by resmaa** [comment]
> I've made some edits. Please review the attached file. I'd like to replace this entry below from <Accessing the Dashboard heading till the end of the document.
> 
> ## Accessing the Dashboard
> **ClusterIP service type**
> 
> 1. When connected to the cluster remotely, run the following command to establish a connection to Dashboard deployment on _port 8080_.
>    `bash kubectl port-forward -n kubernetes-dashboard service/kubernetes-dashboard 8080:443`
> 2. To access the **Kubernetes Dashboard**, go to a web browser of your choice and type:
>    `https://localhost:8080`.
> 3. From a Terminal window, type the following command to get the Bearer token for the **Dashboard Login** page:
>    `bash kubectl -n kubernetes-dashboard describe secret $(kubectl -n kubernetes-dashboard get secret | grep kubernetes-dashboard-token | awk '{print $1}')`
>    The output of the above command will look like this, where the token value is in the last line.
>    ```yaml
>    Name:         kubernetes-dashboard-token-h4lnf
>    Namespace:    kubernetes-dashboard
>    Labels:       <none>
>    Annotations:  kubernetes.io/service-account.name: kubernetes-dashboard
>                kubernetes.io/service-account.uid: 00e729f1-6638-4e68-8df5-afa2e2e38095
>    
>    Type:  kubernetes.io/service-account-token
>    
>    Data
>    ====
>    ca.crt:     1029 bytes
>    namespace:  20 bytes
>    token:      eyJhbGciOiJSUzI1NiIsImtpZCI6Ilg1bTg3RWM4Y1c3NnhkQ3dXbXNDUXQydVpYQklRUWoxa1BaS0ctVkVTSDQifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlcm5ldGVzLWRhc2hib2FyZCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJrdWJlcm5ldGVzLWRhc2hib2FyZC10b2tlbi1oNGxuZiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJrdWJlcm5ldGVzLWRhc2hib2FyZCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjAwZTcyOWYxLTY2MzgtNGU2OC04ZGY1LWFmYTJlMmUzODA5NSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlcm5ldGVzLWRhc2hib2FyZDprdWJlcm5ldGVzLWRhc2hib2FyZCJ9.JU4GOJNjGpkHabUyxBt_2rvtXNjpR3w238BF2oMCQUNf_ZkUGSMeAAgIKxbAuk62dtJNDaRh5yAZ9J5KthMcU6k4qVmodUOJdlvigBVNjTDEhPM-sqJus62HMtwjpvm0CX-aP_A_BqHs2yJ3OgXSX0uHmkUO1FMoZSVaRpOvx7f5bPswxd87L3npuZt4p-NJIX32-DGjBnxdANAHcWil3YHIUbDgQIdjDfN6stGU_JByvzfCJpNCWWDinr772W7iZ3uA28F8uGS0ZMd1E5e1moEFBY8BM015Qxg2Y_k7lmv9S8GMkBJyTiJNiqnwLwfsiE1ycE4Tgq_vuQfFToIMNw
>    ```
> 
> **LoadBalancer service type**
> 
> Use the _LoadBalancer_ Service IP & Port to connect to the Dashboard.
> 
> ## Ingress
> Follow these steps to configure Ingress on the **Kubernetes Dashboard**:
> 
> 1. Change the serviceType from _LoadBalancer_ to _ClusterIP_ (line [integrations start #17](https://github.com/spectrocloud/librarium/pull/17)).
> 2. Ingress (line [Mihai/fixes #23](https://github.com/spectrocloud/librarium/pull/23))
>    
>    * Enable Ingress - change **Enabled** from _false_ to _true_.
>    * Set Ingress rules like **annotations**, **path**, **hosts**, etc.
> 
> With these config changes, you can access the **Kubernetes Dashboard** service on the Ingress Controller LoadBalancer hostname/IP.
> 
> ## Troubleshooting
> If the **Kubernetes Dashboard** is not accessible, check the Dashboard pod for errors and ensure the Dashboard service is in the _Running_ state.
> 
> When the **Namespace** is customized while deploying **Kubernetes Dashboard**, make sure to replace the **Namespace** values in the above commands.
> 
> ## References
> https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/ https://github.com/kubernetes/dashboard/tree/master/docs https://kubernetes.io/docs/concepts/services-networking/ingress/

'bash' not required for kubectl commands

**Review by Siboney1 — APPROVED** [review]

**Comment by spectro-prow** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/spectrocloud/librarium/pull/617#" title="Author self-approved">resmaa</a>*, *<a href="https://github.com/spectrocloud/librarium/pull/617#pullrequestreview-908096993" title="Approved">Siboney1</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=spectrocloud%2Flibrarium).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/spectrocloud/librarium/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by Siboney1** [comment]
Move the word bash from the line so the commands start with the word kubectl.

**Comment by resmaa** [comment]
> Move the word bash from the line so the commands start with the word kubectl.

I have not added bash in the command, I think u added 'bash' in the review 
plz see the snapshot of existing doc attached
image

**Comment by Siboney1** [comment]
> > Move the word bash from the line so the commands start with the word kubectl.
> 
> I have not added bash in the command, I think u added 'bash' in the review plz see the snapshot of existing doc attached image

The word bash is in the original document. See the examples below. 

Screen Shot 2022-03-13 at 10 10 35 AM

Screen Shot 2022-03-13 at 10 11 17 AM


My error is with me adding bash on the same line and that makes it appear on the same line as the Kubectl code. If we include bash above the code, as listed in the original document, it will produce the result that is listed in your example above. I believe the original writer intended to include the word bash, so let's keep it as they wrote it.

**Pull request merged**
