### PR TITLE
tag-update-permission

### PR DESCRIPTION
**Pull request by resmaa**
tag update permission update

### CODE REVIEW

**Comment by spectro-prow** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/spectrocloud/librarium/pull/1085#" title="Author self-approved">resmaa</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=spectrocloud%2Flibrarium).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/spectrocloud/librarium/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by spectro-prow** [comment]
@resmaa: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
librarium_build | 0ef6151bb41c9ca17e317e2dd4933ef7889f67b5 | [link](http://34.120.121.77/view/gcs/capi-prow-artifacts/pr-logs/pull/spectrocloud_librarium/1085/librarium_build/1615299353734287360) | `/test librarium_build`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by karl-cardenas-coding** [comment]
@resmaa a couple of questions come to mind. 

- Does the tenant viewer role not have the ability to view tags?
- I don't see any of the roles having the ability to create, delete, or list tags. Something needs to have the ability to create, delete and list. I create tags when creating cluster profiles as an admin, so I know tenant admins at least have that ability.

**Review by karl-cardenas-coding — COMMENTED** [review]
Awaiting answers to questions asked.

**Comment by revathynallappan** [comment]
@karl-cardenas-coding @resmaa For tags, we have only tag.update permission.  We wanted to restrict the users from updating the tag after the Tag based resource roles has been introduced.

Ex, For a user1, we have given 'ResourceClusterAdmin' roles matching the tags 'tag1'. So to make sure the 'user1' should not update this tag we have introduced this permission 'tag.update'

Viewing tags is fine for all roles.

**Comment by karl-cardenas-coding** [comment]
@revathynallappan What about the Tenant Viewer role? Shouldn't that also have the ability to view tags?

**Comment by revathynallappan** [comment]
@karl-cardenas-coding We don't specifically assign tag.get permission for any roles, by default all roles will have tag.get permission.

**Comment by karl-cardenas-coding** [comment]
@revathynallappan And how will users know that? That's why we need to document it.

**Comment by revathynallappan** [comment]
@karl-cardenas-coding In doc we could mention that all users by default could able to view the resource that they have access to.

**Review by revathynallappan — APPROVED** [review]

**Comment by spectro-prow** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/spectrocloud/librarium/pull/1085#" title="Author self-approved">resmaa</a>*, *<a href="https://github.com/spectrocloud/librarium/pull/1085#pullrequestreview-1268631171" title="Approved">revathynallappan</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=spectrocloud%2Flibrarium).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/spectrocloud/librarium/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
