### PR TITLE
[Snyk] Upgrade sharp from 0.30.5 to 0.32.0

### PR DESCRIPTION
**Pull request by karl-cardenas-coding**
<p>This PR was automatically created by Snyk using the credentials of a real user.</p><br /><h3>Snyk has created this PR to upgrade sharp from 0.30.5 to 0.32.0.</h3>

:information_source: Keep your dependencies up-to-date. This makes it easier to fix existing vulnerabilities and to more quickly identify and fix newly disclosed vulnerabilities when they affect your project.
<hr/>

- The recommended version is **7 versions** ahead of your current version.
- The recommended version was released **21 days ago**, on 2023-03-24.

<details>
<summary><b>Release notes</b></summary>
<br/>
  <details>
    <summary>Package name: <b>sharp</b></summary>
    <ul>
      <li>
        <b>0.32.0</b> - <a href="https://snyk.io/redirect/github/lovell/sharp/releases/tag/v0.32.0">2023-03-24</a></br>No content.
      </li>
      <li>
        <b>0.31.3</b> - <a href="https://snyk.io/redirect/github/lovell/sharp/releases/tag/v0.31.3">2022-12-21</a></br>No content.
      </li>
      <li>
        <b>0.31.2</b> - <a href="https://snyk.io/redirect/github/lovell/sharp/releases/tag/v0.31.2">2022-11-04</a></br>No content.
      </li>
      <li>
        <b>0.31.1</b> - <a href="https://snyk.io/redirect/github/lovell/sharp/releases/tag/v0.31.1">2022-09-29</a></br>No content.
      </li>
      <li>
        <b>0.31.0</b> - <a href="https://snyk.io/redirect/github/lovell/sharp/releases/tag/v0.31.0">2022-09-05</a></br>No content.
      </li>
      <li>
        <b>0.30.7</b> - <a href="https://snyk.io/redirect/github/lovell/sharp/releases/tag/v0.30.7">2022-06-22</a></br>No content.
      </li>
      <li>
        <b>0.30.6</b> - <a href="https://snyk.io/redirect/github/lovell/sharp/releases/tag/v0.30.6">2022-05-30</a></br>No content.
      </li>
      <li>
        <b>0.30.5</b> - <a href="https://snyk.io/redirect/github/lovell/sharp/releases/tag/v0.30.5">2022-05-23</a></br>No content.
      </li>
    </ul>
    from <a href="https://snyk.io/redirect/github/lovell/sharp/releases">sharp GitHub release notes</a>
  </details>
</details>

<details>
  <summary><b>Commit messages</b></summary>
  </br>
  <details>
    <summary>Package name: <b>sharp</b></summary>
    <ul>
      <li><a href="https://snyk.io/redirect/github/lovell/sharp/commit/b9d4c30a9fe203672259a0ef99d3551e6e456114">b9d4c30</a> Release v0.32.0</li>
      <li><a href="https://snyk.io/redirect/github/lovell/sharp/commit/148760fe5564ecaacb1560f5d2ba51306d4b42c9">148760f</a> Docs: clarify resize reduction/enlargement options refer to scaling</li>
      <li><a href="https://snyk.io/redirect/github/lovell/sharp/commit/98ed2377341f9736bfb0431d0380537a184ae252">98ed237</a> Docs: use only first year of copyright to match code</li>
      <li><a href="https://snyk.io/redirect/github/lovell/sharp/commit/b55e58f31e946550b18807d30ac706b7dda36615">b55e58f</a> Trim space from end of libvips error messages</li>
      <li><a href="https://snyk.io/redirect/github/lovell/sharp/commit/0af070ed93791ed7616b892c803471df1122fc99">0af070e</a> Docs: update performance results, include PNG-based task</li>
      <li><a href="https://snyk.io/redirect/github/lovell/sharp/commit/9fbb4fcaef1c08c7cc1e31802419c03b6dd2ee2e">9fbb4fc</a> Tests: bump benchmark deps</li>
      <li><a href="https://snyk.io/redirect/github/lovell/sharp/commit/6008ff8a087adb678e00e3f838833670856a4fba">6008ff8</a> Docs: tile-based output requires libgsf</li>
      <li><a href="https://snyk.io/redirect/github/lovell/sharp/commit/cd5e11bd5084c8a8faa783bb2803dceed1474223">cd5e11b</a> Docs: ensure parameters are indexed as they now appear in a table</li>
      <li><a href="https://snyk.io/redirect/github/lovell/sharp/commit/08d6822265c9ea4cc6170a2bf3d542ea36d2e9aa">08d6822</a> Upgrade to libvips v8.14.2</li>
      <li><a href="https://snyk.io/redirect/github/lovell/sharp/commit/8b8a815fbb654ee4d180313745acaa7355e0a200">8b8a815</a> Tests: tile-based output optional, will require custom libvips</li>
      <li><a href="https://snyk.io/redirect/github/lovell/sharp/commit/a44da850c196efc7711f0ac6ce28b4d0fc88f784">a44da85</a> Docs: add open graph title and image</li>
      <li><a href="https://snyk.io/redirect/github/lovell/sharp/commit/c5ef4677b1302054ed848d1c829d4ca212f1ee4a">c5ef467</a> Bump tsd dep to pick up TypeScript 5 improvements</li>
      <li><a href="https://snyk.io/redirect/github/lovell/sharp/commit/f8a430bdd3ca43575848ecd7bda8b2e5a407689c">f8a430b</a> Tests: reduce CPU cost of RGBA linear test, ~2s faster</li>
      <li><a href="https://snyk.io/redirect/github/lovell/sharp/commit/cd419a261b049bc97c501aaebcb3761e79278a14">cd419a2</a> Docs: changelog and refresh for #3583</li>
      <li><a href="https://snyk.io/redirect/github/lovell/sharp/commit/d7776e3b9812d12ac158046a0b8737b50bef11f6">d7776e3</a> Add support to normalise for lower and upper percentiles (#3583)</li>
      <li><a href="https://snyk.io/redirect/github/lovell/sharp/commit/1eefd4e562fa109e419aa0c83d78fb53b64d11b6">1eefd4e</a> Docs: how to provide new integrity values for custom binaries</li>
      <li><a href="https://snyk.io/redirect/github/lovell/sharp/commit/0a16d26ec794469fece05e8c18d86ee270894b48">0a16d26</a> Docs: fix sharp_binary_host example by adding version (#3568)</li>
      <li><a href="https://snyk.io/redirect/github/lovell/sharp/commit/fc03fba6021f2b24275d7cc2edc7390f229b7543">fc03fba</a> Docs: clarify metadata ignores chained ops</li>
      <li><a href="https://snyk.io/redirect/github/lovell/sharp/commit/c87fe512b4e96e4754f149ac55a508e441bd015b">c87fe51</a> Bump devDeps</li>
      <li><a href="https://snyk.io/redirect/github/lovell/sharp/commit/2eaab59c48fda65fdc60e06faad23f8e4b6bde0c">2eaab59</a> Docs: add note about API Gateway integration</li>
      <li><a href="https://snyk.io/redirect/github/lovell/sharp/commit/4ec883eaa0938b638c7c536ed81391b3e5d50238">4ec883e</a> Wrap all async JS callbacks, help avoid possible race #3569</li>
      <li><a href="https://snyk.io/redirect/github/lovell/sharp/commit/0063df4d4f345471a73a8e08cd73be18d432cfbb">0063df4</a> Ensure clahe op uses random read, simplify validation</li>
      <li><a href="https://snyk.io/redirect/github/lovell/sharp/commit/6c61ad256f4ce6925f927408a1e2e33907aa5e5f">6c61ad2</a> Ensure all source code files contain SPDX licence</li>
      <li><a href="https://snyk.io/redirect/github/lovell/sharp/commit/b90474affa8f08bc646568771092283d17b696d6">b90474a</a> Docs: clarify formats that support multi-page/anim</li>
    </ul>

   <a href="https://snyk.io/redirect/github/lovell/sharp/compare/db654de385e06ee6c56a05aa11a11a2e2f781b14...b9d4c30a9fe203672259a0ef99d3551e6e456114">Compare</a>
  </details>
</details>
<hr/>

**Note:** *You are seeing this because you or someone else with access to this repository has authorized Snyk to open upgrade PRs.*

For more information:  

🧐 [View latest project report](https://app.snyk.io/org/karl-gna/project/3ec260b4-eb0f-4900-9b11-44493bb585f9?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr)

🛠 [Adjust upgrade PR settings](https://app.snyk.io/org/karl-gna/project/3ec260b4-eb0f-4900-9b11-44493bb585f9/settings/integration?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr)

🔕 [Ignore this dependency or unsubscribe from future upgrade PRs](https://app.snyk.io/org/karl-gna/project/3ec260b4-eb0f-4900-9b11-44493bb585f9/settings/integration?pkg&#x3D;sharp&amp;utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr#auto-dep-upgrades)

### CODE REVIEW

**Comment by spectro-prow** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/spectrocloud/librarium/pull/1243#" title="Author self-approved">karl-cardenas-coding</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=spectrocloud%2Flibrarium).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/spectrocloud/librarium/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by spectro-prow** [comment]
@karl-cardenas-coding: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
librarium_build | 4c354b91f6e5f18a4f2d927879e8633a19a04e56 | [link](http://34.120.121.77/view/gcs/capi-prow-artifacts/pr-logs/pull/spectrocloud_librarium/1243/librarium_build/1647032807811190784) | `/test librarium_build`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Review by ritawatson — APPROVED** [review]
LGTM

**Comment by spectro-prow** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/spectrocloud/librarium/pull/1243#" title="Author self-approved">karl-cardenas-coding</a>*, *<a href="https://github.com/spectrocloud/librarium/pull/1243#pullrequestreview-1391073698" title="Approved">ritawatson</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=spectrocloud%2Flibrarium).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/spectrocloud/librarium/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by spectro-prow** [comment]
@karl-cardenas-coding: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
librarium_build | 8200d31d29ffaede4ab091ef93e5f95293bec497 | [link](http://34.120.121.77/view/gcs/capi-prow-artifacts/pr-logs/pull/spectrocloud_librarium/1243/librarium_build/1651592278000537600) | `/test librarium_build`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by spectro-prow** [comment]
@karl-cardenas-coding: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
librarium_build | 59913bd2e5058b5c0c3372952517374ddea10627 | [link](http://34.120.121.77/view/gcs/capi-prow-artifacts/pr-logs/pull/spectrocloud_librarium/1243/librarium_build/1653818528303681536) | `/test librarium_build`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by spectro-prow** [comment]
@karl-cardenas-coding: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
librarium_build | bc028dcecec539af60bc04f94649c7cbeec8fa87 | [link](http://34.120.121.77/view/gcs/capi-prow-artifacts/pr-logs/pull/spectrocloud_librarium/1243/librarium_build/1657387629991170048) | `/test librarium_build`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Pull request merged**
