### PR TITLE
CI Broken URLs

### PR DESCRIPTION
**Pull request by karl-cardenas-coding**
## Describe the Change

This PR adds automation to help the docs team keep up with identifying broken URLs in production.

### CODE REVIEW

**Comment by spectro-prow** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/spectrocloud/librarium/pull/1209#" title="Author self-approved">karl-cardenas-coding</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=spectrocloud%2Flibrarium).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/spectrocloud/librarium/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by karl-cardenas-coding** [comment]
TEST

**Comment by karl-cardenas-coding** [comment]
:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

:sparkles: Object:
:rocket:

**Comment by karl-cardenas-coding** [comment]
:loudspeaker: Object:
:robot: 0: 0
:robot: 1: 0.1
:robot: 2: 0.2
:robot: 3: 0.3
:robot: 4: 0.4
:robot: 5: 0.5
:robot: 6: 0.6
:robot: 7: 0.7
:robot: 8: 0.8
:robot: 9: 0.9
:robot: 10: 0.1
:robot: 11: 0.11
:robot: 12: 0.12
:robot: 13: 0.13
:robot: 14: 0.14
:robot: 15: 0.15
:robot: 16: 0.16
:robot: 17: 0.17
:robot: 18: 0.18
:robot: 19: 0.19
:robot: 20: 0.2
:robot: 21: 0.21
:robot: 22: 0.22
:robot: 23: 0.23
:robot: 24: 0.24
:robot: 25: 0.25
:robot: 26: 0.26
:robot: 27: 0.27
:robot: 28: 0.28
:robot: 29: 0.29
:robot: 30: 0.3
:robot: 31: 0.31
:news:

:loudspeaker: Object:
:news:

**Comment by karl-cardenas-coding** [comment]
# Broken Links in Production Report

**Comment by karl-cardenas-coding** [comment]
# Broken Links in Production Report

**Comment by karl-cardenas-coding** [comment]
# Broken Links in Production Report

**Comment by karl-cardenas-coding** [comment]
# Broken Links Report

:link: [https://docs.spectrocloud.com/clusters/public-cloud/aks/](https://docs.spectrocloud.com/clusters/public-cloud/aks/)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/
---

:link: [https://docs.spectrocloud.com/clusters/public-cloud/eks/](https://docs.spectrocloud.com/clusters/public-cloud/eks/)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/
---

:link: [https://docs.spectrocloud.com/getting-started/free-cloud-credit](https://docs.spectrocloud.com/getting-started/free-cloud-credit)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/getting-started/
---

:link: [https://docs.spectrocloud.com/component/integrations/cilium](https://docs.spectrocloud.com/component/integrations/cilium)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/component
---

:link: [https://docs.spectrocloud.com/clusters/edge/native](https://docs.spectrocloud.com/clusters/edge/native)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/release-notes
---

:link: [https://docs.spectrocloud.com/knowledgebase/how-to/reverse-proxy-dashboard](https://docs.spectrocloud.com/knowledgebase/how-to/reverse-proxy-dashboard)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/release-notes
---

:link: [https://docs.spectrocloud.com/clusters/public-cloud/eks](https://docs.spectrocloud.com/clusters/public-cloud/eks)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/release-notes
---

:link: [https://docs.spectrocloud.com/clusters/public-cloud/aks](https://docs.spectrocloud.com/clusters/public-cloud/aks)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/release-notes
---

:link: [https://docs-latest.spectrocloud.com/clusters/public-cloud/aks](https://docs-latest.spectrocloud.com/clusters/public-cloud/aks)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/release-notes
---

:link: [https://api.spectrocloud.com/](https://api.spectrocloud.com/)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/api/postman-collection
---

:link: [https://docs.spectrocloud.com/clusters/public-cloud/cluster-creation-videos/azure.mp4](https://docs.spectrocloud.com/clusters/public-cloud/cluster-creation-videos/azure.mp4)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/clusters/public-cloud/azure/create-azure-cluster
---

:link: [https://docs.spectrocloud.com/clusters/cluster-management/reverse-proxy-dashboard](https://docs.spectrocloud.com/clusters/cluster-management/reverse-proxy-dashboard)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/integrations/kubernetes-dashboard
---

:link: [https://docs.spectrocloud.com/clusters/data-center/maas/register-manage-mass-cloud-accounts](https://docs.spectrocloud.com/clusters/data-center/maas/register-manage-mass-cloud-accounts)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/clusters/data-center/maas/install-manage-maas-pcg
---

:link: [https://docs.spectrocloud.com/devx/app-profile/service-listings](https://docs.spectrocloud.com/devx/app-profile/service-listings)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/devx/app-profile
---

:link: [https://docs.spectrocloud.com/devx/registries/helm-registry](https://docs.spectrocloud.com/devx/registries/helm-registry)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/devx/registries
---

:link: [https://docs.spectrocloud.com/devx/registries/oci-registry](https://docs.spectrocloud.com/devx/registries/oci-registry)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/devx/registries
---

:link: [https://docs.spectrocloud.com/clusters/edge/stylus-reference](https://docs.spectrocloud.com/clusters/edge/stylus-reference)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/clusters/edge/deployment/native
---

:link: [https://docs.spectrocloud.com/clusters/edge/installer-image](https://docs.spectrocloud.com/clusters/edge/installer-image)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/clusters/edge/deployment/native
---

:link: [https://docs.spectrocloud.com/clusters/edge/cloud-init](https://docs.spectrocloud.com/clusters/edge/cloud-init)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/clusters/edge/deployment/native
---

:link: [https://docs.spectrocloud.com/devx/cluster-groups](https://docs.spectrocloud.com/devx/cluster-groups)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/clusters/cluster-groups/ingress-cluster-group
---

:link: [https://docs.spectrocloud.com/vm-management/create-manage-vm/standard-vm-operations/vm-management/create-manage-vm/standard-vm-operations/migrate-vm-to-different-node](https://docs.spectrocloud.com/vm-management/create-manage-vm/standard-vm-operations/vm-management/create-manage-vm/standard-vm-operations/migrate-vm-to-different-node)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/vm-management/create-manage-vm/standard-vm-operations
---

:link: [https://docs.spectrocloud.com/vm-management/create-manage-vm/standard-vm-operations/vm-management/create-manage-vm/standard-vm-operations/clone-vm](https://docs.spectrocloud.com/vm-management/create-manage-vm/standard-vm-operations/vm-management/create-manage-vm/standard-vm-operations/clone-vm)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/vm-management/create-manage-vm/standard-vm-operations
---

:link: [https://docs.spectrocloud.com/clusters/cluster-groups/ingress-cluster-group/devx/cluster-groups/ingress-cluster-group](https://docs.spectrocloud.com/clusters/cluster-groups/ingress-cluster-group/devx/cluster-groups/ingress-cluster-group)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/clusters/cluster-groups/ingress-cluster-group
---

:link: [https://docs.spectrocloud.com/clusters/edge/edge-configuration/stylus-reference](https://docs.spectrocloud.com/clusters/edge/edge-configuration/stylus-reference)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/clusters/edge/edge-configuration
---

:link: [https://docs.spectrocloud.com/clusters/public-cloud/azure/cluster-creation-videos/azure.mp4](https://docs.spectrocloud.com/clusters/public-cloud/azure/cluster-creation-videos/azure.mp4)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/clusters/public-cloud/azure/create-azure-cluster/
---

:link: [https://docs.spectrocloud.com/clusters/cluster-management/cluster-tag-filter/global-cutome-rroles](https://docs.spectrocloud.com/clusters/cluster-management/cluster-tag-filter/global-cutome-rroles)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/user-management/palette-rbac/resource-scope-roles-permissions
---

:link: [https://docs.spectrocloud.com/devx/app-profile/services/service-listings/redis-db/console.spectrocloud.com](https://docs.spectrocloud.com/devx/app-profile/services/service-listings/redis-db/console.spectrocloud.com)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/devx/app-profile/services/service-listings/redis-db
---

:link: [https://docs.spectrocloud.com/devx/app-profile/services/service-listings/postgresql-db/console.spectrocloud.com](https://docs.spectrocloud.com/devx/app-profile/services/service-listings/postgresql-db/console.spectrocloud.com)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/devx/app-profile/services/service-listings/postgresql-db
---

:link: [https://docs.spectrocloud.com/devx/app-profile/services/service-listings/mongo-db/console.spectrocloud.com](https://docs.spectrocloud.com/devx/app-profile/services/service-listings/mongo-db/console.spectrocloud.com)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/devx/app-profile/services/service-listings/mongo-db
---

:link: [https://docs.spectrocloud.com/devx/app-profile/services/service-listings/mysql/console.spectrocloud.com](https://docs.spectrocloud.com/devx/app-profile/services/service-listings/mysql/console.spectrocloud.com)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/devx/app-profile/services/service-listings/mysql
---

:link: [https://docs.spectrocloud.com/clusters/edge/site-deployment/prepare-edge-configuration](https://docs.spectrocloud.com/clusters/edge/site-deployment/prepare-edge-configuration)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/clusters/edge/site-deployment/model-profile
---

:link: [https://docs.spectrocloud.com/clusters/edge/site-deployment/prepare-content-bundle](https://docs.spectrocloud.com/clusters/edge/site-deployment/prepare-content-bundle)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/clusters/edge/site-deployment/site-installation
---

**Comment by karl-cardenas-coding** [comment]
# Broken Links in Production Report

**Comment by karl-cardenas-coding** [comment]
# Broken Links in Production Report

:link: [https://docs.spectrocloud.com/clusters/public-cloud/eks/](https://docs.spectrocloud.com/clusters/public-cloud/eks/)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/
---

:link: [https://docs.spectrocloud.com/clusters/public-cloud/aks/](https://docs.spectrocloud.com/clusters/public-cloud/aks/)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/
---

:link: [https://docs.spectrocloud.com/getting-started/free-cloud-credit](https://docs.spectrocloud.com/getting-started/free-cloud-credit)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/getting-started/
---

:link: [https://docs.spectrocloud.com/component/integrations/cilium](https://docs.spectrocloud.com/component/integrations/cilium)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/component
---

:link: [https://docs.spectrocloud.com/clusters/public-cloud/aks](https://docs.spectrocloud.com/clusters/public-cloud/aks)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/release-notes
---

:link: [https://docs.spectrocloud.com/clusters/edge/native](https://docs.spectrocloud.com/clusters/edge/native)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/release-notes
---

:link: [https://docs.spectrocloud.com/knowledgebase/how-to/reverse-proxy-dashboard](https://docs.spectrocloud.com/knowledgebase/how-to/reverse-proxy-dashboard)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/release-notes
---

:link: [https://docs.spectrocloud.com/clusters/public-cloud/eks](https://docs.spectrocloud.com/clusters/public-cloud/eks)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/release-notes
---

:link: [https://docs-latest.spectrocloud.com/clusters/public-cloud/aks](https://docs-latest.spectrocloud.com/clusters/public-cloud/aks)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/release-notes
---

:link: [https://api.spectrocloud.com/](https://api.spectrocloud.com/)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/api/postman-collection
---

:link: [https://docs.spectrocloud.com/clusters/cluster-management/reverse-proxy-dashboard](https://docs.spectrocloud.com/clusters/cluster-management/reverse-proxy-dashboard)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/integrations/kubernetes-dashboard
---

:link: [https://docs.spectrocloud.com/devx/registries/oci-registry](https://docs.spectrocloud.com/devx/registries/oci-registry)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/devx/registries
---

:link: [https://docs.spectrocloud.com/devx/app-profile/service-listings](https://docs.spectrocloud.com/devx/app-profile/service-listings)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/devx/app-profile
---

:link: [https://docs.spectrocloud.com/devx/registries/helm-registry](https://docs.spectrocloud.com/devx/registries/helm-registry)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/devx/registries
---

:link: [https://docs.spectrocloud.com/clusters/public-cloud/cluster-creation-videos/azure.mp4](https://docs.spectrocloud.com/clusters/public-cloud/cluster-creation-videos/azure.mp4)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/clusters/public-cloud/azure/create-azure-cluster
---

:link: [https://docs.spectrocloud.com/clusters/data-center/maas/register-manage-mass-cloud-accounts](https://docs.spectrocloud.com/clusters/data-center/maas/register-manage-mass-cloud-accounts)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/clusters/data-center/maas/install-manage-maas-pcg
---

:link: [https://docs.spectrocloud.com/vm-management/create-manage-vm/standard-vm-operations/vm-management/create-manage-vm/standard-vm-operations/clone-vm](https://docs.spectrocloud.com/vm-management/create-manage-vm/standard-vm-operations/vm-management/create-manage-vm/standard-vm-operations/clone-vm)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/vm-management/create-manage-vm/standard-vm-operations
---

:link: [https://docs.spectrocloud.com/vm-management/create-manage-vm/standard-vm-operations/vm-management/create-manage-vm/standard-vm-operations/migrate-vm-to-different-node](https://docs.spectrocloud.com/vm-management/create-manage-vm/standard-vm-operations/vm-management/create-manage-vm/standard-vm-operations/migrate-vm-to-different-node)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/vm-management/create-manage-vm/standard-vm-operations
---

:link: [https://docs.spectrocloud.com/devx/cluster-groups](https://docs.spectrocloud.com/devx/cluster-groups)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/clusters/cluster-groups/ingress-cluster-group
---

:link: [https://docs.spectrocloud.com/clusters/cluster-groups/ingress-cluster-group/devx/cluster-groups/ingress-cluster-group](https://docs.spectrocloud.com/clusters/cluster-groups/ingress-cluster-group/devx/cluster-groups/ingress-cluster-group)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/clusters/cluster-groups/ingress-cluster-group
---

:link: [https://docs.spectrocloud.com/clusters/edge/cloud-init](https://docs.spectrocloud.com/clusters/edge/cloud-init)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/clusters/edge/deployment/native
---

:link: [https://docs.spectrocloud.com/clusters/edge/installer-image](https://docs.spectrocloud.com/clusters/edge/installer-image)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/clusters/edge/deployment/native
---

:link: [https://docs.spectrocloud.com/clusters/edge/stylus-reference](https://docs.spectrocloud.com/clusters/edge/stylus-reference)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/clusters/edge/deployment/native
---

:link: [https://docs.spectrocloud.com/clusters/public-cloud/azure/cluster-creation-videos/azure.mp4](https://docs.spectrocloud.com/clusters/public-cloud/azure/cluster-creation-videos/azure.mp4)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/clusters/public-cloud/azure/create-azure-cluster/
---

:link: [https://docs.spectrocloud.com/clusters/edge/edge-configuration/stylus-reference](https://docs.spectrocloud.com/clusters/edge/edge-configuration/stylus-reference)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/clusters/edge/edge-configuration
---

:link: [https://docs.spectrocloud.com/clusters/cluster-management/cluster-tag-filter/global-cutome-rroles](https://docs.spectrocloud.com/clusters/cluster-management/cluster-tag-filter/global-cutome-rroles)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/user-management/palette-rbac/resource-scope-roles-permissions
---

:link: [https://docs.spectrocloud.com/devx/app-profile/services/service-listings/redis-db/console.spectrocloud.com](https://docs.spectrocloud.com/devx/app-profile/services/service-listings/redis-db/console.spectrocloud.com)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/devx/app-profile/services/service-listings/redis-db
---

:link: [https://docs.spectrocloud.com/devx/app-profile/services/service-listings/mysql/console.spectrocloud.com](https://docs.spectrocloud.com/devx/app-profile/services/service-listings/mysql/console.spectrocloud.com)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/devx/app-profile/services/service-listings/mysql
---

:link: [https://docs.spectrocloud.com/devx/app-profile/services/service-listings/postgresql-db/console.spectrocloud.com](https://docs.spectrocloud.com/devx/app-profile/services/service-listings/postgresql-db/console.spectrocloud.com)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/devx/app-profile/services/service-listings/postgresql-db
---

:link: [https://docs.spectrocloud.com/devx/app-profile/services/service-listings/mongo-db/console.spectrocloud.com](https://docs.spectrocloud.com/devx/app-profile/services/service-listings/mongo-db/console.spectrocloud.com)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/devx/app-profile/services/service-listings/mongo-db
---

:link: [https://docs.spectrocloud.com/clusters/edge/site-deployment/prepare-edge-configuration](https://docs.spectrocloud.com/clusters/edge/site-deployment/prepare-edge-configuration)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/clusters/edge/site-deployment/model-profile
---

:link: [https://docs.spectrocloud.com/clusters/edge/site-deployment/prepare-content-bundle](https://docs.spectrocloud.com/clusters/edge/site-deployment/prepare-content-bundle)  
:traffic_light: Status: 404  
:bookmark_tabs: State: BROKEN  
:arrow_up: Parent: https://docs.spectrocloud.com/clusters/edge/site-deployment/site-installation
---

**Pull request merged**
