### PR TITLE
chore: Add a custom admonition for Tech Preview content

### PR DESCRIPTION
**Pull request by yuliiiah**
## Describe the Change

This PR includes a custom admonition for Tech Preview content.

```
:::preview
:::
```

## Review Changes

💻 [Nutanix](https://deploy-preview-2017--docs-spectrocloud.netlify.app/clusters/data-center/nutanix/)
💻 [Harbor Edge](https://deploy-preview-2017--docs-spectrocloud.netlify.app/integrations/harbor-edge/)
💻 [Vxlan Overlay](https://deploy-preview-2017--docs-spectrocloud.netlify.app/clusters/edge/networking/vxlan-overlay/)

🎫 [DOC-1017](https://spectrocloud.atlassian.net/browse/DOC-1017)

### CODE REVIEW

**Review by karl-cardenas-coding — COMMENTED** [review]
@yuliiiah  can you make the components use a default text with the ability to override. I'd love for us to standardize on the tech preview language 😀

**Comment by lennessyy** [comment]
Looks great! @yuliiiah  Can you go into each of the Preview features and change the adminition to `preview`? That way we can see a real preview?

I think these are the preview features:
- Nutanix
- Harbor Edge
- Edge - Network overlay

Let me know if you have trouble finding these

**Comment by yuliiiah** [comment]
> @yuliiiah can you make the components use a default text with the ability to override. I'd love for us to standardize on the tech preview language 😀

If I remember correctly, you, @lennessyy, and the team agreed on this wording (and it's in the style guide):
> XXX is a Tech Preview feature and is subject to change. Do not use this feature in production workloads.

Based on this template, we want to explicitly specify what feature we're talking about, so it's not really something I can hardcode. Do you think it would be a persistent issue to copy and paste this text from the style guide?

**Comment by karl-cardenas-coding** [comment]
Do we need to name the feature? I think if we keep the language generic we'll be fine

**Comment by yuliiiah** [comment]
@karl-cardenas-coding I've hardcoded the tech preview text. Now, if someone wants to add this admonition, it will always render the same text, even if they try to enter something different

@lennessyy I've added preview links for the pages you mentioned

**Review by karl-cardenas-coding — APPROVED** [review]
Looks fantastic. Thank you so much for creating this 💯

**Comment by yuliiiah** [comment]
Happy to help @karl-cardenas-coding :) Also, since we're already here, let me quickly remind you: https://www.merriam-webster.com/dictionary/vacation

**Comment by lennessyy** [comment]
Hi @yuliiiah , it looks like the auto backport failed for version 4.2. Putting this on your radar in case you missed it.

**Comment by yuliiiah** [comment]
> Hi @yuliiiah , it looks like the auto backport failed for version 4.2. Putting this on your radar in case you missed it.

Oh wow, @lennessyy, thank you so much! I totally missed this. Will backport tomorrow once we're done with Prettier :)

**Pull request merged**
