### PR TITLE
Add Kubecost integration doc

### PR DESCRIPTION
**Pull request by linhlam-kc**
## Describe the Change

This PR add new integration doc for Kubecost pack, a Kubernetes cost monitoring solution.

## Review Changes

💻 [Preview URL](https://github.com/linhlam-kc/librarium/blob/kubecost-new-pack-integ/content/docs/06-integrations/00-kubecost.md)

### CODE REVIEW

**Comment by spectro-prow** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/spectrocloud/librarium/pull/1263#" title="Author self-approved">linhlam-kc</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=spectrocloud%2Flibrarium).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/spectrocloud/librarium/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by spectro-prow** [comment]
Welcome @linhlam-kc! It looks like this is your first PR to spectrocloud/librarium 🎉

**Comment by spectro-prow** [comment]
Hi @linhlam-kc. Thanks for your PR.

I'm waiting for a [spectrocloud](https://github.com/orgs/spectrocloud/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/spectrocloud/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=spectrocloud%2Flibrarium).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Review by karl-cardenas-coding — CHANGES_REQUESTED** [review]
@linhlam-kc We cannot accept this PR in its current form as it does not follow the required style layout of our documentation for Packs.  Here is an [example](https://docs.spectrocloud.com/integrations/prometheus-agent) you can use as a reference.

**Comment by linhlam-kc** [comment]
@karl-cardenas-coding Thank you for your feedback. Can you share what I have missed or what are the required style? I used https://docs.spectrocloud.com/integrations/prometheus-agent/ as an example for this PR. Best, Linh.

**Comment by karl-cardenas-coding** [comment]
@linhlam-kc Take a peek at the example I linked to in my previous comment. I'm also adding the layout guide we are converting all packs to. The other thing I would focus on is addressing the user and using an active voice. Only use "we" when providing a recommendation or an action completed by us. Hope this helps.

[DE-How-toLayout-280423-1730.pdf](https://github.com/spectrocloud/librarium/files/11355976/DE-How-toLayout-280423-1730.pdf)

**Comment by karl-cardenas-coding** [comment]
This PR has not had any activity in the past 30 days. I am closing this PR.

**Pull request closed without merging**
