### PR TITLE
docs: set toc_max_heading_level to default value 3 for all docs DOC-938

### PR DESCRIPTION
**Pull request by addetz**
## Describe the Change

This patch makes the following changes:
- sets the `toc_max_heading_level` to default value 3
- removes redundant frontmatter settings for this level

## Review Changes

💻 [Add Preview URL]()

🎫 [Jira Ticket](https://spectrocloud.atlassian.net/browse/DOC-938)

### CODE REVIEW

**Comment by karl-cardenas-coding** [comment]
@addetz will this also apply to the API plugin ID? We use two plugins to display our docs, the main or default one, and another one for API docs.

**Comment by addetz** [comment]
> @addetz will this also apply to the API plugin ID? We use two plugins to display our docs, the main or default one, and another one for API docs.

Hi @karl-cardenas-coding! Yes, both the plugins use the same theme and this will change them both. Now that you mention it, I'm not sure this is the desired behaviour 🤔

**Comment by karl-cardenas-coding** [comment]
@addetz I think for now we're good but yeah I agree that ideally, the two are decoupled for more flexibility.

**Review by karl-cardenas-coding — APPROVED** [review]

**Comment by addetz** [comment]
Merged into `version-3-4` through cherry-pick 
https://github.com/spectrocloud/librarium/commit/56bd6e38140e5617d5ef41486caf1cc2b9cefb95

**Pull request merged**
